'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
var EVENT_NEW_MESSAGE = 'newMessage';

exports.EVENT_NEW_MESSAGE = EVENT_NEW_MESSAGE;
var IO = 'io';

exports.IO = IO;
var EVENT_PREFIX = 'eventPrefix';

exports.EVENT_PREFIX = EVENT_PREFIX;
var RECORD_ACTIVE = 'recordActive';
exports.RECORD_ACTIVE = RECORD_ACTIVE;
var RECORD_ACTIVE_PER_MEMBER = 'recordActivePerMember';

exports.RECORD_ACTIVE_PER_MEMBER = RECORD_ACTIVE_PER_MEMBER;
var CHAT_MEMORY = 'chatMemory';
exports.CHAT_MEMORY = CHAT_MEMORY;
var CHAT_MEMORY_TTL = 'chatMemoryTtl';
exports.CHAT_MEMORY_TTL = CHAT_MEMORY_TTL;
var CHAT_MEMORY_PROVIDER = 'chatMemoryProvider';
exports.CHAT_MEMORY_PROVIDER = CHAT_MEMORY_PROVIDER;
var CHAT_RECORD_COUNT_MESSAGES = 'chatRecordCountMessages';
exports.CHAT_RECORD_COUNT_MESSAGES = CHAT_RECORD_COUNT_MESSAGES;
var CHAT_RECORD_LAST_MESSAGES = 'chatRecordLastMessages';
exports.CHAT_RECORD_LAST_MESSAGES = CHAT_RECORD_LAST_MESSAGES;
var CHAT_RECORD_LAST_MESSAGES_COUNT = 'chatRecordLastMessagesCount';
exports.CHAT_RECORD_LAST_MESSAGES_COUNT = CHAT_RECORD_LAST_MESSAGES_COUNT;
var CHAT_SINGLE_PRIVATE = 'chatSinglePrivate';
exports.CHAT_SINGLE_PRIVATE = CHAT_SINGLE_PRIVATE;
var CHAT_NEW_ON_GROUP = 'chatNewOnGroup';
exports.CHAT_NEW_ON_GROUP = CHAT_NEW_ON_GROUP;
var CHAT_AUTOREAD_ON_ACTIVE = 'chatAutoreadOnActive';
exports.CHAT_AUTOREAD_ON_ACTIVE = CHAT_AUTOREAD_ON_ACTIVE;
var CHAT_SYSTEM_NOTIFICATION = 'chatSystemNotification';
exports.CHAT_SYSTEM_NOTIFICATION = CHAT_SYSTEM_NOTIFICATION;
var CHAT_MEMBER_WRITE = 'chatMemberWrite';

exports.CHAT_MEMBER_WRITE = CHAT_MEMBER_WRITE;
var MESSAGE_RECORD_READ = 'messageRecordRead';
exports.MESSAGE_RECORD_READ = MESSAGE_RECORD_READ;
var MESSAGE_RECORD_DELETE = 'messageRecordDelete';
exports.MESSAGE_RECORD_DELETE = MESSAGE_RECORD_DELETE;
var MESSAGE_RECORD_MEMBERS = 'messageRecordMembers';
exports.MESSAGE_RECORD_MEMBERS = MESSAGE_RECORD_MEMBERS;
var MESSAGE_RECORD_EDIT = 'messageRecordEdit';

exports.MESSAGE_RECORD_EDIT = MESSAGE_RECORD_EDIT;
var MEMBER_ONLINE = 'memberOnline';
exports.MEMBER_ONLINE = MEMBER_ONLINE;
var MEMBER_STATUS = 'memberStatus';
exports.MEMBER_STATUS = MEMBER_STATUS;
var MEMBER_CONTACTS = 'memberContacts';
exports.MEMBER_CONTACTS = MEMBER_CONTACTS;
//# sourceMappingURL=options.js.map